### ISSUE TITLE
강력해지고 있다구요

### ISSUE THREAD

**Issue by audtjddld** [audtjddld/spring-crawler-sample#3]
@LichKing-lee 어서 은혜주세요.

event로 죄다 빼버렸습니다.

cafe24 도와주세요.

**Comment by audtjddld** [comment]
@kingseam
cafe24 갑시다. 도와주십쇼

**Comment by kingseam** [comment]
@LichKing-lee 존경그자체

**Comment by audtjddld** [comment]
@kingseam 도와주세요 도와주세요 도와주세요!!!

**Comment by reiphiel** [comment]
@LichKing-lee 존경!!

**Comment by audtjddld** [comment]
@reiphiel
도와주십쇼 도와주십쇼

**Comment by LichKing-lee** [comment]
존경합니다.

**Comment by audtjddld** [comment]
@LichKing-lee [브런치](https://github.com/audtjddld/crawler-sample/tree/feature/apply-selenium) 봐달라구욧.

**Comment by audtjddld** [comment]
왜 안봐주세요.. 이슈 종료하겠습니다

**Comment by reiphiel** [comment]
'강력해지고 있다구요'라는 이슈명을 보고 개발에 착수하지 못했어요 ㅠㅠ
